### 2.4. Содержание файла с NumPy

В файле `HW01.ipynb` должны быть:

1. Импорт библиотеки NumPy с общепринятым сокращением.
2. Примеры создания массивов:
   - из обычных списков;
   - с использованием функций `zeros`, `ones`, `arange` или аналогичных.
3. Демонстрация атрибутов:
   - вывод формы (shape) и типа данных (dtype) для одного из массивов.
4. Примеры индексирования и срезов:
   - получение отдельного элемента;
   - извлечение подмассива с помощью среза.
5. Примеры векторных операций и базовых статистик:
   - поэлементное сложение или умножение массивов;
   - вычисление средней величины (`mean`) или другой простой статистики.

In [32]:
import numpy as np

arr1 = np.zeros((5,5), dtype = int) #создание массива из нулей

arr2 = np.ones((5,5), dtype = int) #создание массива из единиц

arr3 = np.array([np.arange(5) for i in range(5)]) #массив из четырех строк от 1 до 4
[print(f"{i}\n") for i in (arr1,arr2,arr3)]

print(f'Форма массива - {np.shape(arr1)}\nТип данных массива - {arr1.dtype}')

print("Обращение к последнему элементу первой строки - ", arr3[1][4], "\nИзвлечение подмассива - ", arr1[1])

print('Умножение - ', arr2*2, "\nМедиана - ", np.median(arr3))

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]

Форма массива - (5, 5)
Тип данных массива - int64
Обращение к последнему элементу первой строки -  4 
Извлечение подмассива -  [0 0 0 0 0]
Умножение -  [[2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]] 
Медиана -  2.0
